[project] # Project metadata
name = "neural-fib-se-bse"
authors = [
  {name = "Tim Dahmen", email = "tim.dahmen@hs-aalen.de"}
]
requires-python = ">=3.12"
readme = "README.md"
license = { "file" = "LICENSE" }
dependencies = ["numpy", "fastai", "tifffile", "scipy", "configparser"]
dynamic = ["version", "description"]

[build-system] # How pip and other frontends should build this project
requires = ["py-build-cmake~=0.4.3"]
build-backend = "py_build_cmake.build"

[tool.py-build-cmake.module] # Where to find the Python module to package
name = "neural_fib_se_bse" # preprocess_module should be under src
directory = "src"		   # 

[tool.py-build-cmake.sdist] # What to include in source distributions
include = ["CMakeLists.txt", "src/native_src/*"]

[tool.py-build-cmake.cmake] # How to build the CMake project
build_type = "Release"
source_path = "src/native_src/"
build_args = ["-j"]
install_components = ["python_modules", "python_stubs"]

[tool.py-build-cmake.stubgen] # Whether and how to generate typed stub files
args = ["-v"]

[tool.py-build-cmake.editable]
mode = "symlink"