[project] # Project metadata
name = "neural_fib_se_bse"
requires-python = ">=3.7"
readme = "README.md"
license = { "file" = "LICENSE" }
dependencies = ["numpy", "numpy-devel", "fastai"]
dynamic = ["version", "description"]

[build-system] # How pip and other frontends should build this project
requires = ["py-build-cmake~=0.4.3"]
build-backend = "py_build_cmake.build"

[tool.py-build-cmake.module] # Where to find the Python module to package
name = "neural_fib_se_bse"
directory = "src"

[tool.py-build-cmake.sdist] # What to include in source distributions
include = ["CmakeLists.txt", "src/native_src"]

[tool.py-build-cmake.cmake] # How to build the CMake project
build_type = "Release"
source_path = "src/native_src/"
build_args = ["-j"]
install_components = ["python_modules"]

[tool.py-build-cmake.stubgen] # Whether and how to generate typed stub files